### ISSUE TITLE
Event id - clarify uniqueness of this

### ISSUE THREAD

**Issue by jimmcslim** [clef-json/clef-json.github.io#1]
Event id - should this be unique for each separate log event, or is it a hash of the message template?

e.g. should the pair of the following events...

````
{"@m": "The temperature is 40 degrees.", "@mt": "The temperature is {DegreesCelsius}", "DegreesCelsius": "40", "@i": "???"}
{"@m": "The temperature is 35 degrees.", "@mt": "The temperature is {DegreesCelsius}", "DegreesCelsius": "35", "@I": "???"}
````

Should `@I` be the same for both of these, since they have the same message template (in which case `@I` is an implementation-specific hash) or should `@I` be completely different (e.g. a UUID).

**Comment by nblumhardt** [comment]
Thanks for the note, @jimmcslim - agreed we should clarify this :+1: 

`@id` is a type, so in your example both events should carry the same value for it.
